"""2025-02-27T16:10:49.666636_add_roles

Revision ID: 3c84a7a33f5d
Revises: 08f2636195ed
Create Date: 2025-02-27 16:10:49.874639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from database.config import DB_CONFIG
from database.model import Model
from services.personality.models import RoleORM, RolesEnum

# revision identifiers, used by Alembic.
revision: str = "3c84a7a33f5d"
down_revision: Union[str, None] = "3b98ed404991"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    engine = create_engine(DB_CONFIG.url)
    session_class = sessionmaker(engine)
    with session_class() as session:
        for role_data in RolesEnum:
            role = RoleORM(name=role_data.value[0], description=role_data.value[-1].capitalize())
            session.add(role)
            session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    engine = create_engine(DB_CONFIG.url)
    session_class = sessionmaker(engine)
    with session_class() as session:
        session.query(RoleORM).filter(RoleORM.name.in_([item.value[0] for item in RolesEnum])).delete(
            synchronize_session="fetch"
        )
        session.commit()
